s3:
  bucket: "medellin-ai"
  path: "audio/"

local:
  audios: "data/audio/"
  images: "data/images/"
  metadata_audios: "data/metadata/esc50.csv"
  image_file_extension: ".png"
  audio_file_extension: ".wav"

huggingface:
  images_dataset_path: "Isamu136/big-animal-dataset"
  audios_dataset_path: "DynamicSuperb/AnimalClassification_WaveSource-Test"
  image_text_model: "openai/clip-vit-base-patch32"
  image_caption_model: "Salesforce/blip-image-captioning-base"

vectordb:
  client: "http://localhost:6333"
  collection_audio: "medellin-ai-audio-vectors"
  collection_image: "medellin-ai-image-vectors"

llm:
  id: "llama3-70b-8192"
  temperature: 1.0